version: "3"
services:
  blog:
    image: ghcr.io/semycolon/vue3-vite-ssr-blog:master
    command: >
      bash -c "npm run prisma:deploy && npm run start"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      JWT_SECRET: "supersecuresecret"
      DATABASE_URL: "postgres://root:password@db/blog"
      VITE_SITE_BRAND_NAME: "Medium"
      VITE_DOMAIN_ADDRESS: "http://localhost:3000"
      MINIO_END_POINT_URL: "0.0.0.0"
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_BUCKET_NAME: "blog"
      MINIO_PORT: "9000"
      MINIO_SSL: "false"
    depends_on:
      - minio
      - createbuckets
  db:
    image: postgres
    restart: always
    volumes:
      - "/tmp/data/db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "blog"
#  adminer:
#      image: adminer
#      restart: always
#      ports:
#        - "127.0.0.1:8080:8080"

  minio:
    image: "minio/minio"
    command: [ "server", "/data" ]
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_BUCKET_NAME: "blog"
      MINIO_PORT: "9000"
      MINIO_SSL: "false"
    volumes:
      - "/tmp/data/minio_data:/data"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 10; 
      /usr/bin/mc alias set star http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb star/"${MINIO_BUCKET_NAME}";
      /usr/bin/mc policy set public star/${MINIO_BUCKET_NAME};
      exit 0;
      "
